BACKGROUND_COLOR = "#1A237E"
FOREGROUND_COLOR = "#FFFFFF"
BUTTON_COLOR = "#B71C1C"
BUTTON_COLOR_NEW = "#000000"
BUTTON_COLOR_HOVER = "#D32F2F"
ENTRY_BACKGROUND = "#37474F"
ENTRY_FOREGROUND = "#FFFFFF"
LABEL_COLOR = "#B0BEC5"
TITLE_COLOR = "#FFFFFF"
SUBTITLE_COLOR = "#CFD8DC"
BUTTON_TEXT_COLOR = "#FFFFFF"
BUTTON_BG_GRADIENT = "#B565A7"

         