
LOGIN_SYSTEM_SCHOOL_SUBTITLE = "Liceo Nacional Jose Felix Ribas"
LOGIN_LABEL_USER = "Usuario:"
LOGIN_LABEL_PASSWORD = "Contraseña:"
LOGIN_BUTTON_LOGIN = "¡Ingresar!"

HOME_SUBTITLE = "Bienvenido al sistema de gestión"
HOME_BUTTON_EDIT = "Editar"
HOME_BUTTON_DELETE = "Borrar"

STUDENT_TITLE_EDIT = "Editar Estudiante"
TEACHER_TITLE_ADD = "Agregar Docente"

GLOBAL_STUDENT_TITLE_ADD = "Agregar Estudiante"
GLOBAL_SYSTEM_SCHOOL_TITLE = "Sistema De Gestión Escolar"
GLOBAL_CONFIRM_DELETE = "Confirmar Borrado"
GLOBAL_BUTTON_SAVE = "Guardar"
GLOBAL_BUTTON_CONFIRM = "Confirmar"
GLOBAL_BUTTON_CANCEL ="Cancelar"
GLOBAL_TABLE_NIT = "Cédula"
GLOBAL_TABLE_NAME = "Nombres"
GLOBAL_TITLE_EDIT = "Editar Docente"
GLOBAL_NAME_AND_SURNAME = "Nombre y Apellido"
GLOBAL_STUDENT = "Estudiante"
GLOBAL_TEACHER = "Docente"
GLOBAL_LAST_NAME = "Apellido"
GLOBAL_AGE = "Edad"
GLOBAL_SEX = "Sexo"
GLOBAL_ADDRESS = "Dirección"
GLOBAL_COURSE = "Año"
GLOBAL_PHONE = "Teléfono"
GLOBAL_SUBJECT = "Asignatura"

GLOBAL_BIRTH_PLACE = "Lugar de Nacimiento"
GLOBAL_BIRTH_DATE = "Fecha de Nacimiento"
GLOBAL_NATIONALITY = "Nacionalidad"
GLOBAL_PREVIOUS_SCHOOL = "Plantel de Procedencia"
GLOBAL_PENDING_SUBJECT = "Trae Materia Pendiente"
GLOBAL_WHICH_SUBJECT = "¿Cuál?"
GLOBAL_REPEATING = "Repite"
GLOBAL_WHICH_SUBJECTS = "¿Con Cuáles?"
GLOBAL_LIVES_WITH_PARENTS = "¿Vive con sus Padres?"
GLOBAL_STUDENT_EMAIL = "Correo Electrónico del Estudiante"
GLOBAL_RELIGION = "Religión"

HEADER = "Encabezado"
FULL_NAME = "Nombre_Completo"
CURRENT_DATE = "fecha_actual"
ISSUE = "fecha_emision"
GENERATE_RECORDS_BUTTON = "generar_constancia"